// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmjanfjavsldyxscituu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtamFuZmphdnNsZHl4c2NpdHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjI4MzksImV4cCI6MjA2MDg5ODgzOX0.C1A3xBiTB8QoZ44BFFbfBvUKuu4VaOmHnlO-Zswx4Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);